### PR TITLE
Reset depth when formatting differences

### PR DESCRIPTION
**Pull request by bunysae**
As i mention in issue [#41](https://github.com/concordancejs/concordance/issues/41) just render the diff with unlimited depth would fix this issue. This can be done with the new option `renderDiffWithUnlimitedDepth`.
Successor for PR #61.

### CODE REVIEW

**Comment by novemberborn** [comment]
Thinking about it, I don't think we should render with unlimited depth. But we could take the max depth and start counting at `0` again for the diffs?

We should make that the default behavior, no option required. What do you think?

**Comment by papb** [comment]
I would be happy with either approach I guess, the depth is just too shallow currently...

**Comment by bunysae** [comment]
I implemented the current indent as offset, when a diff is reached.
Now it gives the result:
```
  [
    Object { … },
+   {
+     d: 'bar',
+     e: 'g',
+     f: Object { … },
+   },
  ]
```
for
```
const o1 = [
        {
                b: 'b'
        },
        {
                d: 'bar',
                e: 'g',
                f: {
                        h: 'h'
                }
        }
];
const o2 = [
        {
                b: 'b'
        }
];

console.log(concordance.diff(o2, o1, {maxDepth: 1}));
```

**Comment by novemberborn** [comment]
@bunysae lovely, thanks!

Could you submit your PR at https://issuehunt.io/r/concordancejs/concordance/issues/41?

**Comment by novemberborn** [comment]
I will try to roll this into the next AVA release, probably this weekend.

**Comment by bunysae** [comment]
@novemberborn
Done. I'm looking forward to the next AVA release.

**Pull request merged**
